### ISSUE TITLE
Enhance Security: Mask/Remove Reduct sensitive spark properties from session info

### ISSUE THREAD

**Issue by katymufler** [exacaster/lighter#1071]
**Description:**

Currently, Lighter session info page may inadvertently expose sensitive information (e.g., database credentials, API keys) as part of spark properties.

I think it would be useful to create a comprehensive list of sensitive Spark properties that should be masked or removed from session info. This could include:
spark.hadoop.hive.metastore.uris
spark.datasource.jdbc.url
Any property containing password, secret, key, etc.

Also Allow users to customize the list of sensitive properties and the masking/removal behavior via configuration options.

Regards, Katy

**Comment by katymufler** [comment]
Thank you! In which release it will be included and when?
Thanks again :)

**Comment by pdambrauskas** [comment]
Hey, it will be included on the next release. We will release it as soon as @Minutis will test our latest changes on his cluster.

**Comment by pdambrauskas** [comment]
It has been released on 0.1.2
