### ISSUE TITLE
how to define json in deployment.yaml environment variable

### ISSUE THREAD

**Issue by cometta** [exacaster/lighter#141]
in the k8s deployment.yaml env section, 
```
env:
    - name: LIGHTER_SESSION_DEFAULT_CONF
       value: { "spark.key1: "value",  "spark.key2": "value"}
```
above is not a valid yaml format to include json snippet. can advice how to do this ? in the example at https://github.com/exacaster/lighter/blob/master/docs/configuration.md ,  Example of LIGHTER_BATCH_DEFAULT_CONF: {"spark.kubernetes.driverEnv.TEST1":"test1"}.  , but how to include this in deployment.yaml env section?

**Comment by Minutis** [comment]
```
                    env:
                        -   name: LIGHTER_SESSION_DEFAULT_CONF
                            value: '{"spark.kubernetes.container.image":"<image>","<conf_key>":"<conf_value>"}'
```
