### ISSUE TITLE
[QST] Where are the env variables defined the configuration page used in the code? 

### ISSUE THREAD

**Issue by wjxiz1992** [exacaster/lighter#266]
Hi, I'm new to lighter and k8s and want to explore the usage.

I find there're some predefined `env` variables in https://github.com/exacaster/lighter/blob/master/docs/configuration.md, for example, 
`LIGHTER_STORAGE_JDBC_URL`. 
I'm curious how this variable is used in the deployment? I try to search it in this repo, but cannot find any code that uses it except the markdown files.

I would like to understand how these variables impact the lighter workflow.

Thanks a lot!

**Comment by Minutis** [comment]
Hello, it overrides https://github.com/exacaster/lighter/blob/master/server/src/main/resources/application.yml#L19 this parameter. And in the end is used here https://github.com/exacaster/lighter/blob/master/server/src/main/java/com/exacaster/lighter/storage/jdbc/LighterJdbcDatasourceConfiguration.java. This is just how Micronaut (and Spring Boot) allows configuring things. https://docs.micronaut.io/latest/guide/index.html#_included_propertysource_loaders

**Comment by wjxiz1992** [comment]
Thanks for the reply real quick!
