### ISSUE TITLE
`python3` not found error when starting Python session

### ISSUE THREAD

**Issue by NiklasRosenstein** [exacaster/lighter#292]
Hey 👋 I was giving Lighter a try in Kubernetes and when I'm trying to start a Python Spark session, I get this error:

![image](https://user-images.githubusercontent.com/1318438/210100680-cd55168b-ba84-4630-8b95-e7a830e4e0c0.png)
![image](https://user-images.githubusercontent.com/1318438/210100698-c21c7f84-5bfd-4ee4-8106-cb78fe11c13f.png)

I believe this is because `python3` is not installed in the Lighter image.

The image I'm using is `ghcr.io/exacaster/lighter:0.0.41-spark3.3.1`

**Comment by pdambrauskas** [comment]
Hi, thanks for trying out Lighter!

It looks like you are running Lighter in local mode, in that case Lighter tries to look for Python inside its own image.

Our documentation for k8s deployment was outdated, I've updated it with missing property:
https://github.com/exacaster/lighter/commit/ef8b9dd187523e41ce2dd182c8f442127090001b

Can you try setting `LIGHTER_KUBERNETES_ENABLED` to "true"?

Also you should probably add `LIGHTER_SESSION_DEFAULT_CONF` with value of
`'{"spark.kubernetes.container.image":"apache/spark-py:3.3.1"}'`, to specify which docker image new Sessions should use by default, when image is not specified by the user on jupyter notebook.

**Comment by NiklasRosenstein** [comment]
Thank you @pdambrauskas, that does put me two steps closer! Now I'm facing an SSL certificate error, but I'll open a separate issue for this.
