### ISSUE TITLE
does lighther has security mechanism with rest api?

### ISSUE THREAD

**Issue by geosmart** [exacaster/lighter#30]
just want to  make sure the rest api not attach by somebody

**Comment by pdambrauskas** [comment]
Hi,
Lighter itself does not have any authentication/authorization mechanisms.
What you can do to protect it form external attacks:
- When deploying on K8s - use ingress middle-wares to add security measures
For example  when using Nginx Ingress controller you can add basic auth: https://kubernetes.github.io/ingress-nginx/examples/auth/basic/
- Deploy Lighter in private network
