### ISSUE TITLE
Ldap authentication support

### ISSUE THREAD

**Issue by rwu-wish** [exacaster/lighter#347]
any plans to support ldap authentication?

Ldap support in livy:
https://github.com/apache/incubator-livy/commit/2e7d691c03caa6eaa1d170b2ab03265a65ff12f2
https://github.com/apache/incubator-livy/commit/9b776a58fdeac63261f988dde70093bdf0191721

**Comment by pdambrauskas** [comment]
Hi,
 we did not plan to implement any type of authorization/authentication, and recommended doing it on ingerss controller side (in case of kubernetes) it works fine for basic authentication, but I'm not sure what are the options for LDAP authentication.
 
 Lighter uses Micronaut framework, it has some kind of integration for LDAP: https://guides.micronaut.io/latest/micronaut-database-authentication-provider-gradle-groovy.html so we would not have to do everything from scratch.
 
 Can you provide us more details on your use-case? 
 Have you used LDAP on your Livy setup?
 How does it integrate with spark-magic?
 How does it look on UI side, does it prompt users with basic auth dialog for user credentials?
