### ISSUE TITLE
History button directs to non existent url if batch on YARN failed

### ISSUE THREAD

**Issue by EmilK322** [exacaster/lighter#35]
When submitting a batch the History IconButton directing to ```{`${conf.sparkHistoryServerUrl}/history/${app.appId}/jobs`}```
This behavior works great on k8s, but when submitting on YARN if the app fails it could have `attempt_id` which is used with the app_id to get the specific attempt run in the spark history server.
Url looks like this:   ```{`${conf.sparkHistoryServerUrl}/history/${app.appId}/${attempt_id}/jobs`}```.

because of that behavior, the link is broken if the app fails with YARN enabled.

I can think of 2 solutions:
1. Fetching the attempts from YARN or history server and using the latest or all of them.
2. change the link to ```{`${conf.sparkHistoryServerUrl}/history/${app.appId}`}```, history server automatically redirecting to /jobs with the latest attempt

The first is more feature-rich, can direct to different attempts, but needs to change the code in a lot of places.
The second is not as feature-rich, but it is simple as possible and keeps the frontend cluster-agnostic as it is right now.

@pdambrauskas, @hynix what do you think about this? 
I would happy to contribute a solution.

**Comment by pdambrauskas** [comment]
Hi, @EmilK322 , thanks for reporting this issue.
I think it would be sufficient to go with 2nd option at this stage of the project. It would be nice to represent all the attempts on the UI, but in that case we'd have to save attempt ids in database, to avoid slow API responses when querying for the list of apps. Not sure if that's worth it.

Please do contribute, if you can. It will be the first external contribution for this project :)
