### ISSUE TITLE
pip install library

### ISSUE THREAD

**Issue by cometta** [exacaster/lighter#376]
Sorry for asking this. Does anyone know when using sparkmagic with lighter, can we install additional python library through jupyter notebook cell so that it is run on spark driver and executors ? What is the sparkmagic command to do this?

**Comment by Minutis** [comment]
Unfortunately, when the Spark application has already started it is not possible to add/remove Python packages dynamically. The main idea is always to build the packages into an image or archive and use it when starting your Spark application. What that means is that it is possible to provide the whole Python environment as an argument during `spark-submit`.

Some more information can be found https://spark.apache.org/docs/latest/api/python/user_guide/python_packaging.html.

If you could specify the use case you have in mind, maybe we could suggest more specific suggestions.
