### ISSUE TITLE
"jars" field for iteractive session type

### ISSUE THREAD

**Issue by wjxiz1992** [exacaster/lighter#388]
Hi, I'd like to know if "jars" field could work in lighter framework. 
I ask this because when I try livy session mode, with the "jars" field in the post payload (e.g.  `"jars": "s3:/abc/def.jar"`), the jars are not properly uploaded, thus when calling class/objects from this def.jar, it says classNotFound etc. But this "jars" amazingly works well for batch mode in livy. (same issue reported: https://community.cloudera.com/t5/Support-Questions/How-to-post-a-Spark-Job-as-JAR-via-Livy-interactive-REST/m-p/299806/highlight/true#M219859 )
Does lighter support the "jars" in interacive session mode? If it does, I can try to promote lighter in our project! thanks for your patients.

**Comment by Minutis** [comment]
Hello @wjxiz1992,

I have just tried the "jars" argument in a session and it looks like it is working. At least I see it load in the logs of the session start.

After adding:
```
...
    "jars": "https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar",
...
```

Job logs:
```
...
23/03/09 16:03:01 INFO SparkContext: Added JAR file:/tmp/spark-ec7ef524-5a11-46d4-9e41-114877390c96/commons-lang3-3.12.0.jar at spark://<ip>:7078/jars/commons-lang3-3.12.0.jar with timestamp 1678377779875
...
```

So it should work for your use case also.

**Comment by wjxiz1992** [comment]
Thanks for the quick reply!
