### ISSUE TITLE
question about storage_jdbc

### ISSUE THREAD

**Issue by itamar-otonomo** [exacaster/lighter#482]
Hi,
Could anyone give an example of a database I could use in an AWS environment?
I tried to put in a redis url, that didn't quite work and I am not sure if dynamodb is supported or how its jdbc URI would look like.

Thanks,
Itamar.

**Comment by pdambrauskas** [comment]
Hi,
- For testing purposes you can use h2 (in-memory) database. When Lighter is launched without provided url, this database is used.
- For Production environment on AWS we are using [Amazon RDS for PostgreSQL](https://aws.amazon.com/rds/postgresql/)
- For any other SQL database you'd have to add additional JDBC driver here: https://github.com/exacaster/lighter/blob/master/server/build.gradle#L57
- For any other storage, [ApplicationStorage](https://github.com/exacaster/lighter/blob/master/server/src/main/java/com/exacaster/lighter/storage/ApplicationStorage.java) interface has to be implemented and contributed to the Lighter project :)

**Comment by itamar-otonomo** [comment]
A thousand thanks!
