### ISSUE TITLE
open to set max executorCores

### ISSUE THREAD

**Issue by cometta** [exacaster/lighter#498]
is there any option i can put in config to set maximum executorCores and driverCores ? currently it set in k8s pod section  `request` but can't set max `limit`

**Comment by Minutis** [comment]
Hello,

from the [Spark documentation](https://spark.apache.org/docs/latest/running-on-kubernetes.html)
> The cpu limits are set by spark.kubernetes.{driver,executor}.limit.cores. The cpu is set by spark.{driver,executor}.cores. The memory request and limit are set by summing the values of spark.{driver,executor}.memory and spark.{driver,executor}.memoryOverhead. Other resource limits are set by spark.{driver,executor}.resources.{resourceName}.* configs.

Please set needed configurations accordingly when submitting the Spark job.
