### ISSUE TITLE
long running juypter notebok session

### ISSUE THREAD

**Issue by cometta** [exacaster/lighter#499]
I ran my jupyter notebook using lighter for training job which take 1 week to finish. is it correct to set this key in lighter to extend the session LIGHTER_SESSION_TIMEOUT_MINUTES. ?  currently i experienced after 1 day overnight, the spark session just exit and i can't find out what the reason. can advice ?

**Comment by pdambrauskas** [comment]
Yes, you are right `LIGHTER_SESSION_TIMEOUT_MINUTES` is used when timing out unused sessions.
Lighter kills the session, when it is not receiving any statements for more than `LIGHTER_SESSION_TIMEOUT_MINUTES`.
