### ISSUE TITLE
how to clear old dangling sessions of notebook

### ISSUE THREAD

**Issue by cometta** [exacaster/lighter#510]
when i start lighter using notebook with config look like
```
%%configure
{"conf": {
   ...
```
after ran the notebook cell, it show list of sessions (id, yarn app id, kind, staate, spark ui, driver log, user, current session?)

how to clear those? it is stored in the DB right?

**Comment by pdambrauskas** [comment]
Yes, sessions, as well as other spark applications are stored on the DB.
You can delete them one-by-one on the Lighter UI. Or directly on database:
```sql
DELETE FROM application WHERE type='SESSION' AND state NOT IN ('IDLE', 'BUSY', 'NOT_STARTED', 'STARTING');
```
