### ISSUE TITLE
matplot serverside rendering supported

### ISSUE THREAD

**Issue by cometta** [exacaster/lighter#514]
May i know is this feature supported
```
%matplot plt
```
or need to install additional plugin in spark magic notebook?

ref: https://github.com/jupyter-incubator/sparkmagic/blob/master/examples/Pyspark%20Kernel.ipynb

let say i have a variable with list of RGB images , how to render it on spark magic cell ? use `%%local`?

**Comment by pdambrauskas** [comment]
Hey,
Lighter does not currently support `%matplot`, looks like some changes has to be made to [command interpreter](https://github.com/exacaster/lighter/blob/master/server/src/main/resources/shell_wrapper.py) for it to work.

**Comment by Minutis** [comment]
Nice, thanks for sharing!
