### ISSUE TITLE
sessions on k8s : url http://lighter.spark:8080 should be configurable 

### ISSUE THREAD

**Issue by julienlau** [exacaster/lighter#595]
Hi,
Thanks for sharing.

There is a configuration issue using session from REST in k8s. 
One url is hard-coded and shoud not.
See https://github.com/exacaster/lighter/blob/99f5235e6103837262d20da2ed3555ab4b6ab70a/server/src/main/resources/application.yml
`url: http://lighter.spark:8080`

This should be user defined and the value should be the name of the service that was created by the user at installation.
For example:
`url: http://spark-lighter-svc.ns-spark.svc.cluster.local:80`

**Comment by pdambrauskas** [comment]
Hey, you can override it with ‘LIGHTER_URL’ environment variable, it is dicumende here: https://github.com/exacaster/lighter/blob/master/docs/configuration.md#global-properties . The hardcoded value, you have mentuoned is the default value for this priperty.

**Comment by julienlau** [comment]
Thanks for the quick answer, my mistake !
