### ISSUE TITLE
LIGHTER_SPARK_HISTORY_SERVER_URL

### ISSUE THREAD

**Issue by cometta** [exacaster/lighter#602]
can elaborate more what is the usage of LIGHTER_SPARK_HISTORY_SERVER_URL instead of just use `spark.eventLog.dir` to save the log and view it later on Spark history server. 

May i know when spark session spun up together with workers pods. can we view the spark UI of the current running spark session? how to view it

**Comment by pdambrauskas** [comment]
Hi,
It is used as an url prefix when showing history button on the Lighte UI: https://github.com/exacaster/lighter/blob/6b4f0be0cdcc975eb0b063810f997db44e5558b9/frontend/src/components/AppActions.tsx#L18
