### ISSUE TITLE
API request to list all statements of a given session

### ISSUE THREAD

**Issue by julienlau** [exacaster/lighter#603]
Hi,

Maybe I missed something in the swagger but found the Get statement by statementID, but I cannot find the "list all statements by sessionID".
Does it exists ?

How would you do to retrieve the state of a statement if you did not catch the statement ID when doing the submit ?

Regards
JL

**Comment by pdambrauskas** [comment]
Hi, just checked it, indeed there is no such API endpoint.
It shouldnt be very hard to implemet it though, we could try to add it on our next release.

What is the use case for it? Are you using Sessions without Jupyter?

**Comment by julienlau** [comment]
Yes I am using Sessions without Jupyter.
The idea is to help users perform trial-error like in jupyter but in an internally built platform.
I want to reuse a single session for all users in the same project and send statements through a centralized workflow orchestrator based on java copper-engine.

**Comment by pdambrauskas** [comment]
I've created a pull request for this, it should be merged for our next release

**Comment by julienlau** [comment]
I tested it and it's fine. thanks
