### ISSUE TITLE
disable log of user code /log in lighter pod

### ISSUE THREAD

**Issue by julienlau** [exacaster/lighter#608]
As is, the default behavior is that the lighter pod logs too much !

It logs: 
- the code submitted through a statement
- the console log of the job "Pi is roughly"

Would it be possible to disable it ?

![image](https://github.com/exacaster/lighter/assets/6950247/48fa4195-b974-4396-8de4-dd59727d95c2)

**Comment by pdambrauskas** [comment]
I've created a pull request changing log level for statement code, and a way to change log level, it should be merged for our next release
