### ISSUE TITLE
Sizing cpu/mem versus number of sessions

### ISSUE THREAD

**Issue by julienlau** [exacaster/lighter#611]
Hi,

The initial settings is maximum 5 batches running  + 5 starting. 
There are no settings on the max number of sessions.
Do you have some idea of the maximum number of sessions ?
Is it ok to have 100 sessions ?
How would you size lighter pod (cpu, mem) in this case in a configuration where the DB is stored on a dedicated postgres ?

During my tests, I stick to 2-3 sessions max and H2:file and I observed that lighter pods goes fine with mem=1GB & cpu=1.

Regards,
JL

**Comment by pdambrauskas** [comment]
In case of the process, which is responsible for launching newly scheduled sessions, it starts max 10 sessions per minute. From what I saw, CPU and memory usage increases significantly, only in cases, when significantly bigger numbers of applications are being launched in parallel. We have this value configurable for batch jobs.

**Comment by julienlau** [comment]
Ok thanks.

If scaling the number of session may be an issue, then it is confusing to have parameters for the max number of batches and not for the max number of sessions.

Unfortunately, I do not have a large k8s cluster to load test lighter with a lot of sessions.

**Comment by Minutis** [comment]
Closing the issue as stale for now.
