### ISSUE TITLE
can explain on LIGHTER_EXTERNAL_LOGS_URL_TEMPLATE

### ISSUE THREAD

**Issue by cometta** [exacaster/lighter#625]
what is the variable LIGHTER_EXTERNAL_LOGS_URL_TEMPLATE for?

**Comment by pdambrauskas** [comment]
If this value is set, you will see a link to external system on The Lighter UI. It is used for cases, when you expose your driver logs to some kind of external system (Graylog, Grafana Loki, etc.), we should probably addd more details about that on our documentations.

**Comment by pdambrauskas** [comment]
I've updated documentation for this property: https://github.com/exacaster/lighter/blob/master/docs/configuration.md
