### ISSUE TITLE
sometime lighter will start 2 different sessions 

### ISSUE THREAD

**Issue by cometta** [exacaster/lighter#626]
on Jupyter notebook, if i press shut down kernel + restart kernel  ( do it fast repeatedly) . sometime lighter will spin up 2 different sessions. that might be due to race condition. just report this see anyone else experience similar issue.

**Comment by Minutis** [comment]
It is highly likely that the issue is with [sparkmagic](https://github.com/jupyter-incubator/sparkmagic) plugin that manages integration between Lither and Jupyter and not with the Lighter itself. Have you noticed that with a single call to Lighter it is creating multiple seasions instead of one?
