### ISSUE TITLE
Docker image build failing for latest master branch

### ISSUE THREAD

**Issue by sumanthssr** [exacaster/lighter#907]
=> CACHED [server 4/5] WORKDIR /home/app/server/                                                                                                         0.0s
 => CANCELED [server 5/5] RUN ./gradlew build -x test -PSPARK_VERSION=3.5.0                                                                               1.3s
 => ERROR [frontend 4/6] RUN wget "https://downloads.apache.org/spark/spark-3.5.0/spark-3.5.0-bin-hadoop3.tgz" -O - | tar -xz

Is there any working branch to build custom lighter image? @Minutis

**Comment by pdambrauskas** [comment]
you should be able to build on https://github.com/exacaster/lighter/pull/908

**Comment by pdambrauskas** [comment]
Hm, strange, I’ll look into it a bit later.

**Comment by pdambrauskas** [comment]
I've fixed Docker file on https://github.com/exacaster/lighter/pull/908. It was failing because of framework update, after which artefact was built under a different path.
