### ISSUE TITLE
bug docker image path

### ISSUE THREAD

**Issue by cometta** [exacaster/lighter#916]
i specified `"spark.kubernetes.container.image"` in `LIGHTER_SESSION_DEFAULT_CONF` , but the juypter notebook can't identify it. in order to work, i need to insert this key in `%%configure` jupyter notebook. Also tested with latest docker image `0.1.0-spark3.5.0` and `0.0.50-spark3.5.0`.   Does `LIGHTER_SESSION_DEFAULT_CONF` key work on latest version of lighter?

**Comment by pdambrauskas** [comment]
Just checked locally it seems to work for me. Can you provide more details, how are you trying to set `LIGHTER_SESSION_DEFAULT_CONF` variable? snippet of your kubernetes deployment configuration maybe?

I've tested it with this this value: `{"spark.kubernetes.container.image":"test"}`

**Comment by pdambrauskas** [comment]
Are you sure you did not have an extra comma when testing on 0.1.0? It seems to work locally for me.

**Comment by pdambrauskas** [comment]
Thanks for detailed response. I see that statement api returns http status 200, while sparkmagic is expecting 201.

It is not related to lighter_session_default_conf. It was probably broken, with one of new features introduced in 0.1.0. 

Will try to fix it and release as soon as possible.

**Comment by pdambrauskas** [comment]
I've prepared an MR for the fix, and built an image for it: ghcr.io/exacaster/lighter:919-spark3.5.1
