### ISSUE TITLE
batch feature

### ISSUE THREAD

**Issue by cometta** [exacaster/lighter#942]
on the lighter ui, I can see a tab call "batch". Can you share any documentation on how to use this feature? Is the job run through jupyter notebook interface or through terminal pyspark code  ?

**Comment by Minutis** [comment]
It all depends on the configurations that you started Lighter with, but basically it should be enough to specify `spark.kubernetes.container.image` when submitting to k8s.

**Comment by Minutis** [comment]
Please provide more information: payload of request to Lighter or just all parameters that are passed to the Lighter.

**Comment by Minutis** [comment]
It's possible but not recommended. Anything you specify in archives will be downloaded to the nodes. if you specify s3a:// prefix - it should work.
