### ISSUE TITLE
use default value for LIGHTER_BATCH_DEFAULT_CONF

### ISSUE THREAD

**Issue by cometta** [exacaster/lighter#962]
can LIGHTER_BATCH_DEFAULT_CONF use same value of LIGHTER_SESSION_DEFAULT_CONF so that no need to duplicate same value for both ? Otherwise, i would need duplicate same values for both key

**Comment by pdambrauskas** [comment]
In most cases these values are different. Things like default resources & default docker image usually differ between sessions and batch applications.

If you are using Helm you can parametrise ENV variables through `values`  file and use the same value for both environment variables.
